#include "about.h"
#include "ui_about.h"

About::About(QWidget *parent) :
    QDialog(parent),
    ui(new Ui::About)
{
    ui->setupUi(this);
    setWindowFlags(Qt::Window | Qt::FramelessWindowHint);

    ui->label_4->setText("were generated by <a href=\"https://creator.nightcafe.studio/\" style=\"color: rgb(247, 194, 15);\">AI</a>");
    ui->label_4->setTextFormat(Qt::RichText);
    ui->label_4->setTextInteractionFlags(Qt::TextBrowserInteraction);
    ui->label_4->setOpenExternalLinks(true);

    ui->label_6->setText("was created by <a href=\"https://www.flaticon.com/free-icons/gold\""
                         "style=\"color: rgb(247, 194, 15);\">wanicon</a>");
    ui->label_6->setTextFormat(Qt::RichText);
    ui->label_6->setTextInteractionFlags(Qt::TextBrowserInteraction);
    ui->label_6->setOpenExternalLinks(true);

    ui->label_10->setText("was created by <a href=\"https://www.flaticon.com/free-icons/crystals\""
                          "style=\"color: rgb(247, 194, 15);\">max.icons</a>");
    ui->label_10->setTextFormat(Qt::RichText);
    ui->label_10->setTextInteractionFlags(Qt::TextBrowserInteraction);
    ui->label_10->setOpenExternalLinks(true);

    ui->label_20->setText("was created by <a href=\"https://www.flaticon.com/free-icons/hammer\""
                          "style=\"color: rgb(247, 194, 15);\">Flaticon</a>");
    ui->label_20->setTextFormat(Qt::RichText);
    ui->label_20->setTextInteractionFlags(Qt::TextBrowserInteraction);
    ui->label_20->setOpenExternalLinks(true);

    ui->label_14->setText("was created by <a href=\"https://www.flaticon.com/free-icons/dynamite\""
                          "style=\"color: rgb(247, 194, 15);\">justicon</a>");
    ui->label_14->setTextFormat(Qt::RichText);
    ui->label_14->setTextInteractionFlags(Qt::TextBrowserInteraction);
    ui->label_14->setOpenExternalLinks(true);

    ui->label_8->setText("was created by <a href=\"https://www.flaticon.com/free-icons/arson\""
                         "style=\"color: rgb(247, 194, 15);\">Flaticon</a>");
    ui->label_8->setTextFormat(Qt::RichText);
    ui->label_8->setTextInteractionFlags(Qt::TextBrowserInteraction);
    ui->label_8->setOpenExternalLinks(true);

    ui->label_12->setText("was created by <a href=\"https://www.flaticon.com/free-icons/pickaxe\""
                          "style=\"color: rgb(247, 194, 15);\">Flaticon</a>");
    ui->label_12->setTextFormat(Qt::RichText);
    ui->label_12->setTextInteractionFlags(Qt::TextBrowserInteraction);
    ui->label_12->setOpenExternalLinks(true);

    ui->label_16->setText("was created by <a href=\"https://www.flaticon.com/free-icons/drill\""
                          "style=\"color: rgb(247, 194, 15);\">Flaticon</a>");
    ui->label_16->setTextFormat(Qt::RichText);
    ui->label_16->setTextInteractionFlags(Qt::TextBrowserInteraction);
    ui->label_16->setOpenExternalLinks(true);

    ui->label_18->setText("was created by <a href=\"https://www.flaticon.com/free-icons/sad\""
                          "style=\"color: rgb(247, 194, 15);\">Flaticon</a>");
    ui->label_18->setTextFormat(Qt::RichText);
    ui->label_18->setTextInteractionFlags(Qt::TextBrowserInteraction);
    ui->label_18->setOpenExternalLinks(true);
}

About::~About()
{
    delete ui;
}

void About::on_xButton_clicked()
{
    close();
}

